### ISSUE TITLE
github.com/akeylesslabs/akeyless-go-sdk No longer exists.

### ISSUE THREAD

**Issue by Just4Ease** [akeylesslabs/akeyless-go#2]
github.com/akeylesslabs/akeyless-go-sdk no longer exists, 
it's now breaking my deployment 😬😬
What's the way forward?

**Comment by AngelRefael** [comment]
Hi @Just4Ease 
github.com/akeylesslabs/akeyless-go-sdk has been deprecated and is no longer supported. You can use https://github.com/akeylesslabs/akeyless-go as an alternative.

**Comment by Just4Ease** [comment]
Ok.

Please how do I get to know when there's a new announcement online?
