### ISSUE TITLE
Shall we use v2 or v3

### ISSUE THREAD

**Issue by betabandido** [akeylesslabs/akeyless-go#7]
Our vulnerability scanner is detecting some issues in indirect dependencies from `github.com/akeylesslabs/akeyless-go/v2`. We have seen there is a v3 in the repository, but the docs (e.g., https://docs.akeyless.io/docs/go#installation) still refer to v2. Yet, v2 has not seen any release since last year.

Is it safe/recommended to use v3?

**Comment by betabandido** [comment]
@tuvia-akeyless @rani-sharim Can you please provide some guidance?

**Comment by rani-sharim** [comment]
@betabandido Yes, you should use `v3`. The docs were not updated properly.

**Comment by betabandido** [comment]
Thank you! :)
